version: "3.8"

services:
  app:
    image: ruby
    command: bash -c "gem install rack sinatra puma pg && ruby import_from_csv.rb && ruby server.rb"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - gems:/usr/local/bundle/gems

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_records

  test-db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_records

volumes:
  db-data:
  gems:
