version: "3.8"

services:
  app:
    image: ruby
    command: bash -c "bundle install && ruby import_from_csv.rb && ruby server.rb"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - bundle-cache:/usr/local/bundle

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_records

  test-db:
    image: postgres
    volumes:
      - test-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_records

volumes:
  db-data:
  test-db-data:
  bundle-cache:
