version: "3.8"

services:
  app:
    image: ruby
    command: bash -c "gem install rack sinatra puma pg && ruby server.rb"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app

  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_records
