version: "3.8"

services:
  app:
    image: ruby
    command: bash -c "bundle install && ruby server.rb"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./app:/app
      - bundle-cache:/usr/local/bundle
    environment:
      APP_ENV: development
      DB: db

  tests:
    image: ruby
    command: bash -c "bundle install && ruby server.rb"
    working_dir: /app
    volumes:
      - ./app:/app
      - ./tests:/tests
      - bundle-cache:/usr/local/bundle
    environment:
      APP_ENV: test
      DB: test-db

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_records

  test-db:
    image: postgres
    volumes:
      - test-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_records

volumes:
  db-data:
  test-db-data:
  bundle-cache:
