version: "3.8"

services:
  app:
    image: ruby
    command: bash -c "bundle && ruby server.rb"
    depends_on:
      - db
      - sidekiq
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./app:/app
      - bundle-cache:/usr/local/bundle
    environment:
      APP_ENV: development
      DB: db
      REDIS_URL: redis://redis:6379

  sidekiq:
    image: ruby
    command: bash -c "bundle && sidekiq -r './import_worker.rb'"
    depends_on:
      - redis
    volumes:
      - ./app:/app
      - sidekiq-bundle-cache:/usr/local/bundle
    working_dir: /app/sidekiq
    environment:
      REDIS_URL: redis://redis:6379

  redis:
    image: redis

  tests:
    image: ruby
    command: bash -c "bundle && ruby server.rb"
    depends_on:
      - test-db
      - sidekiq
    working_dir: /app
    volumes:
      - ./app:/app
      - ./tests:/tests
      - bundle-cache:/usr/local/bundle
    environment:
      APP_ENV: test
      DB: test-db
      REDIS_URL: redis://redis:6379

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_records

  test-db:
    image: postgres
    volumes:
      - test-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_records

volumes:
  db-data:
  test-db-data:
  bundle-cache:
  sidekiq-bundle-cache:
